#!/usr/bin/env bash
# B-002: Regression Testing
# SC-8: Key workflows produce same artifacts under plugin-based install
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== Workflow 1: spec CREATE ==="
echo "Baseline (symlink install):"
echo "  1. Use current symlink-based setup"
echo "  2. Run: /spec CREATE specs/2026/02/test/000-regression-test.md"
echo "  3. Record: exit code, created files, file content structure"
echo ""
echo "Plugin install:"
echo "  1. Load via: claude --plugin-dir $REPO_ROOT/plugins/agentic-spec"
echo "  2. Run same: /spec CREATE specs/2026/02/test/000-regression-test.md"
echo "  3. Compare: exit code, created files, file content structure"
echo ""
echo "Pass criteria: Same file created, same section structure, no path errors"
echo ""

echo "=== Workflow 2: o_spec ==="
echo "Baseline (symlink install):"
echo "  1. Run: /o_spec <existing-spec>"
echo "  2. Record: exit code, output format"
echo ""
echo "Plugin install:"
echo "  1. Load agentic-spec plugin"
echo "  2. Run same o_spec command"
echo "  3. Compare output"
echo ""
echo "Pass criteria: Same output format, no path-resolution errors"
echo ""

echo "=== Workflow 3: pull_request ==="
echo "Baseline (symlink install):"
echo "  1. Run: /pull_request (on a branch with changes)"
echo "  2. Record: exit code, PR created/output"
echo ""
echo "Plugin install:"
echo "  1. Load agentic-git plugin"
echo "  2. Run same pull_request command"
echo "  3. Compare output"
echo ""
echo "Pass criteria: Same behavior, no missing file errors"
echo ""

echo "=== Path resolution verification ==="
echo "Key paths that must resolve under plugin install:"
echo "  - Spec agents: \${CLAUDE_PLUGIN_ROOT}/agents/ (agentic-spec)"
echo "  - Spec resolver lib: requires AGENTIC_GLOBAL path (outside plugin)"
echo "  - Hook scripts: \${CLAUDE_PLUGIN_ROOT}/scripts/hooks/ (agentic, agentic-tools)"
echo ""
echo "Known risk: spec-resolver.sh sources from AGENTIC_GLOBAL, not plugin cache."
echo "This is by design -- spec-resolver is a global lib, not plugin-specific."
echo ""

echo "=== PASS/FAIL checklist ==="
echo "[ ] SC-8: spec CREATE -- same file artifacts, no path errors"
echo "[ ] SC-8: o_spec -- same output, no path errors"
echo "[ ] SC-8: pull_request -- same behavior, no path errors"
echo "[ ] SC-8: No path-resolution errors in any workflow"
